### ISSUE TITLE
Unexpected non-whitespace character after JSON at position 5682

### ISSUE THREAD

**Issue by Habubinator** [SwapnilSoni1999/16personalities-api#2]
At GET https://www.16personalities-api.com/api/personality/questions

Error 500 : {
    "message": "Unexpected non-whitespace character after JSON at position 5682"
}

And on POST /api/personality/submit with 
```JSON
{
    "answers": [
    {
        "id": "WW91IHJlZ3VsYXJseSBtYWtlIG5ldyBmcmllbmRzLg",
        "value": 0
    },
    {
        "id": "Q29tcGxleCBhbmQgbm92ZWwgaWRlYXMgZXhjaXRlIHlvdSBtb3JlIHRoYW4gc2ltcGxlIGFuZCBzdHJhaWdodGZvcndhcmQgb25lcy4",
        "value": -3
    },
    {
        "id": "WW91IHVzdWFsbHkgZmVlbCBtb3JlIHBlcnN1YWRlZCBieSB3aGF0IHJlc29uYXRlcyBlbW90aW9uYWxseSB3aXRoIHlvdSB0aGFuIGJ5IGZhY3R1YWwgYXJndW1lbnRzLg",
        "value": -3
    },
    {
        "id": "WW91ciBsaXZpbmcgYW5kIHdvcmtpbmcgc3BhY2VzIGFyZSBjbGVhbiBhbmQgb3JnYW5pemVkLg",
        "value": 0
    },
    {
        "id": "WW91IHVzdWFsbHkgc3RheSBjYWxtLCBldmVuIHVuZGVyIGEgbG90IG9mIHByZXNzdXJlLg",
        "value": 2
    },
    {
        "id": "WW91IGZpbmQgdGhlIGlkZWEgb2YgbmV0d29ya2luZyBvciBwcm9tb3RpbmcgeW91cnNlbGYgdG8gc3RyYW5nZXJzIHZlcnkgZGF1bnRpbmcu",
        "value": -2
    },
    {
        "id": "WW91IHByaW9yaXRpemUgYW5kIHBsYW4gdGFza3MgZWZmZWN0aXZlbHksIG9mdGVuIGNvbXBsZXRpbmcgdGhlbSB3ZWxsIGJlZm9yZSB0aGUgZGVhZGxpbmUu",
        "value": -1
    },
    {
        "id": "UGVvcGxl4oCZcyBzdG9yaWVzIGFuZCBlbW90aW9ucyBzcGVhayBsb3VkZXIgdG8geW91IHRoYW4gbnVtYmVycyBvciBkYXRhLg",
        "value": -2
    },
    {
        "id": "WW91IGxpa2UgdG8gdXNlIG9yZ2FuaXppbmcgdG9vbHMgbGlrZSBzY2hlZHVsZXMgYW5kIGxpc3RzLg",
        "value": 0
    },
    {
        "id": "RXZlbiBhIHNtYWxsIG1pc3Rha2UgY2FuIGNhdXNlIHlvdSB0byBkb3VidCB5b3VyIG92ZXJhbGwgYWJpbGl0aWVzIGFuZCBrbm93bGVkZ2Uu",
        "value": -3
    },
    {
        "id": "WW91IGZlZWwgY29tZm9ydGFibGUganVzdCB3YWxraW5nIHVwIHRvIHNvbWVvbmUgeW91IGZpbmQgaW50ZXJlc3RpbmcgYW5kIHN0cmlraW5nIHVwIGEgY29udmVyc2F0aW9uLg",
        "value": 2
    },
    {
        "id": "WW91IGFyZSBub3QgdG9vIGludGVyZXN0ZWQgaW4gZGlzY3Vzc2lvbnMgYWJvdXQgdmFyaW91cyBpbnRlcnByZXRhdGlvbnMgb2YgY3JlYXRpdmUgd29ya3Mu",
        "value": 3
    },
    {
        "id": "WW91IHByaW9yaXRpemUgZmFjdHMgb3ZlciBwZW9wbGXigJlzIGZlZWxpbmdzIHdoZW4gZGV0ZXJtaW5pbmcgYSBjb3Vyc2Ugb2YgYWN0aW9uLg",
        "value": 3
    },
    {
        "id": "WW91IG9mdGVuIGFsbG93IHRoZSBkYXkgdG8gdW5mb2xkIHdpdGhvdXQgYW55IHNjaGVkdWxlIGF0IGFsbC4",
        "value": -2
    },
    {
        "id": "WW91IHJhcmVseSB3b3JyeSBhYm91dCB3aGV0aGVyIHlvdSBtYWtlIGEgZ29vZCBpbXByZXNzaW9uIG9uIHBlb3BsZSB5b3UgbWVldC4",
        "value": 3
    },
    {
        "id": "WW91IGVuam95IHBhcnRpY2lwYXRpbmcgaW4gdGVhbS1iYXNlZCBhY3Rpdml0aWVzLg",
        "value": 2
    },
    {
        "id": "WW91IGVuam95IGV4cGVyaW1lbnRpbmcgd2l0aCBuZXcgYW5kIHVudGVzdGVkIGFwcHJvYWNoZXMu",
        "value": -1
    },
    {
        "id": "WW91IHByaW9yaXRpemUgYmVpbmcgc2Vuc2l0aXZlIG92ZXIgYmVpbmcgY29tcGxldGVseSBob25lc3Qu",
        "value": -3
    },
    {
        "id": "WW91IGFjdGl2ZWx5IHNlZWsgb3V0IG5ldyBleHBlcmllbmNlcyBhbmQga25vd2xlZGdlIGFyZWFzIHRvIGV4cGxvcmUu",
        "value": 3
    },
    {
        "id": "WW91IGFyZSBwcm9uZSB0byB3b3JyeWluZyB0aGF0IHRoaW5ncyB3aWxsIHRha2UgYSB0dXJuIGZvciB0aGUgd29yc2Uu",
        "value": -2
    },
    {
        "id": "WW91IGVuam95IHNvbGl0YXJ5IGhvYmJpZXMgb3IgYWN0aXZpdGllcyBtb3JlIHRoYW4gZ3JvdXAgb25lcy4",
        "value": -2
    },
    {
        "id": "WW91IGNhbm5vdCBpbWFnaW5lIHlvdXJzZWxmIHdyaXRpbmcgZmljdGlvbmFsIHN0b3JpZXMgZm9yIGEgbGl2aW5nLg",
        "value": 3
    },
    {
        "id": "WW91IGZhdm9yIGVmZmljaWVuY3kgaW4gZGVjaXNpb25zLCBldmVuIGlmIGl0IG1lYW5zIGRpc3JlZ2FyZGluZyBzb21lIGVtb3Rpb25hbCBhc3BlY3RzLg",
        "value": 3
    },
    {
        "id": "WW91IHByZWZlciB0byBkbyB5b3VyIGNob3JlcyBiZWZvcmUgYWxsb3dpbmcgeW91cnNlbGYgdG8gcmVsYXgu",
        "value": 3
    },
    {
        "id": "SW4gZGlzYWdyZWVtZW50cywgeW91IHByaW9yaXRpemUgcHJvdmluZyB5b3VyIHBvaW50IG92ZXIgcHJlc2VydmluZyB0aGUgZmVlbGluZ3Mgb2Ygb3RoZXJzLg",
        "value": 0
    },
    {
        "id": "WW91IHVzdWFsbHkgd2FpdCBmb3Igb3RoZXJzIHRvIGludHJvZHVjZSB0aGVtc2VsdmVzIGZpcnN0IGF0IHNvY2lhbCBnYXRoZXJpbmdzLg",
        "value": 1
    },
    {
        "id": "WW91ciBtb29kIGNhbiBjaGFuZ2UgdmVyeSBxdWlja2x5Lg",
        "value": 2
    },
    {
        "id": "WW91IGFyZSBub3QgZWFzaWx5IHN3YXllZCBieSBlbW90aW9uYWwgYXJndW1lbnRzLg",
        "value": -3
    },
    {
        "id": "WW91IG9mdGVuIGVuZCB1cCBkb2luZyB0aGluZ3MgYXQgdGhlIGxhc3QgcG9zc2libGUgbW9tZW50Lg",
        "value": 0
    },
    {
        "id": "WW91IGVuam95IGRlYmF0aW5nIGV0aGljYWwgZGlsZW1tYXMu",
        "value": -3
    },
    {
        "id": "WW91IHVzdWFsbHkgcHJlZmVyIHRvIGJlIGFyb3VuZCBvdGhlcnMgcmF0aGVyIHRoYW4gb24geW91ciBvd24u",
        "value": 2
    },
    {
        "id": "WW91IGJlY29tZSBib3JlZCBvciBsb3NlIGludGVyZXN0IHdoZW4gdGhlIGRpc2N1c3Npb24gZ2V0cyBoaWdobHkgdGhlb3JldGljYWwu",
        "value": 0
    },
    {
        "id": "V2hlbiBmYWN0cyBhbmQgZmVlbGluZ3MgY29uZmxpY3QsIHlvdSB1c3VhbGx5IGZpbmQgeW91cnNlbGYgZm9sbG93aW5nIHlvdXIgaGVhcnQu",
        "value": 2
    },
    {
        "id": "WW91IGZpbmQgaXQgY2hhbGxlbmdpbmcgdG8gbWFpbnRhaW4gYSBjb25zaXN0ZW50IHdvcmsgb3Igc3R1ZHkgc2NoZWR1bGUu",
        "value": -2
    },
    {
        "id": "WW91IHJhcmVseSBzZWNvbmQtZ3Vlc3MgdGhlIGNob2ljZXMgdGhhdCB5b3UgaGF2ZSBtYWRlLg",
        "value": 3
    },
    {
        "id": "WW91ciBmcmllbmRzIHdvdWxkIGRlc2NyaWJlIHlvdSBhcyBsaXZlbHkgYW5kIG91dGdvaW5nLg",
        "value": 3
    },
    {
        "id": "WW91IGFyZSBkcmF3biB0byB2YXJpb3VzIGZvcm1zIG9mIGNyZWF0aXZlIGV4cHJlc3Npb24sIHN1Y2ggYXMgd3JpdGluZy4",
        "value": 3
    },
    {
        "id": "WW91IHVzdWFsbHkgYmFzZSB5b3VyIGNob2ljZXMgb24gb2JqZWN0aXZlIGZhY3RzIHJhdGhlciB0aGFuIGVtb3Rpb25hbCBpbXByZXNzaW9ucy4",
        "value": 3
    },
    {
        "id": "WW91IGxpa2UgdG8gaGF2ZSBhIHRvLWRvIGxpc3QgZm9yIGVhY2ggZGF5Lg",
        "value": 1
    },
    {
        "id": "WW91IHJhcmVseSBmZWVsIGluc2VjdXJlLg",
        "value": 3
    },
    {
        "id": "WW91IGF2b2lkIG1ha2luZyBwaG9uZSBjYWxscy4",
        "value": -3
    },
    {
        "id": "WW91IGVuam95IGV4cGxvcmluZyB1bmZhbWlsaWFyIGlkZWFzIGFuZCB2aWV3cG9pbnRzLg",
        "value": 0
    },
    {
        "id": "WW91IGNhbiBlYXNpbHkgY29ubmVjdCB3aXRoIHBlb3BsZSB5b3UgaGF2ZSBqdXN0IG1ldC4",
        "value": 2
    },
    {
        "id": "SWYgeW91ciBwbGFucyBhcmUgaW50ZXJydXB0ZWQsIHlvdXIgdG9wIHByaW9yaXR5IGlzIHRvIGdldCBiYWNrIG9uIHRyYWNrIGFzIHNvb24gYXMgcG9zc2libGUu",
        "value": 3
    },
    {
        "id": "WW91IGFyZSBzdGlsbCBib3RoZXJlZCBieSBtaXN0YWtlcyB0aGF0IHlvdSBtYWRlIGEgbG9uZyB0aW1lIGFnby4",
        "value": 0
    },
    {
        "id": "WW91IGFyZSBub3QgdG9vIGludGVyZXN0ZWQgaW4gZGlzY3Vzc2luZyB0aGVvcmllcyBvbiB3aGF0IHRoZSB3b3JsZCBjb3VsZCBsb29rIGxpa2UgaW4gdGhlIGZ1dHVyZS4",
        "value": 0
    },
    {
        "id": "WW91ciBlbW90aW9ucyBjb250cm9sIHlvdSBtb3JlIHRoYW4geW91IGNvbnRyb2wgdGhlbS4",
        "value": -3
    },
    {
        "id": "V2hlbiBtYWtpbmcgZGVjaXNpb25zLCB5b3UgZm9jdXMgbW9yZSBvbiBob3cgdGhlIGFmZmVjdGVkIHBlb3BsZSBtaWdodCBmZWVsIHRoYW4gb24gd2hhdCBpcyBtb3N0IGxvZ2ljYWwgb3IgZWZmaWNpZW50Lg",
        "value": -2
    },
    {
        "id": "WW91ciBwZXJzb25hbCB3b3JrIHN0eWxlIGlzIGNsb3NlciB0byBzcG9udGFuZW91cyBidXJzdHMgb2YgZW5lcmd5IHRoYW4gb3JnYW5pemVkIGFuZCBjb25zaXN0ZW50IGVmZm9ydHMu",
        "value": -3
    },
    {
        "id": "V2hlbiBzb21lb25lIHRoaW5rcyBoaWdobHkgb2YgeW91LCB5b3Ugd29uZGVyIGhvdyBsb25nIGl0IHdpbGwgdGFrZSB0aGVtIHRvIGZlZWwgZGlzYXBwb2ludGVkIGluIHlvdS4",
        "value": -3
    },
    {
        "id": "WW91IHdvdWxkIGxvdmUgYSBqb2IgdGhhdCByZXF1aXJlcyB5b3UgdG8gd29yayBhbG9uZSBtb3N0IG9mIHRoZSB0aW1lLg",
        "value": -2
    },
    {
        "id": "WW91IGJlbGlldmUgdGhhdCBwb25kZXJpbmcgYWJzdHJhY3QgcGhpbG9zb3BoaWNhbCBxdWVzdGlvbnMgaXMgYSB3YXN0ZSBvZiB0aW1lLg",
        "value": 2
    },
    {
        "id": "WW91IGZlZWwgbW9yZSBkcmF3biB0byBidXN5LCBidXN0bGluZyBhdG1vc3BoZXJlcyB0aGFuIHRvIHF1aWV0LCBpbnRpbWF0ZSBwbGFjZXMu",
        "value": 3
    },
    {
        "id": "SWYgYSBkZWNpc2lvbiBmZWVscyByaWdodCB0byB5b3UsIHlvdSBvZnRlbiBhY3Qgb24gaXQgd2l0aG91dCBuZWVkaW5nIGZ1cnRoZXIgcHJvb2Yu",
        "value": 2
    },
    {
        "id": "WW91IG9mdGVuIGZlZWwgb3ZlcndoZWxtZWQu",
        "value": 3
    },
    {
        "id": "WW91IGNvbXBsZXRlIHRoaW5ncyBtZXRob2RpY2FsbHkgd2l0aG91dCBza2lwcGluZyBvdmVyIGFueSBzdGVwcy4",
        "value": 2
    },
    {
        "id": "WW91IHByZWZlciB0YXNrcyB0aGF0IHJlcXVpcmUgeW91IHRvIGNvbWUgdXAgd2l0aCBjcmVhdGl2ZSBzb2x1dGlvbnMgcmF0aGVyIHRoYW4gZm9sbG93IGNvbmNyZXRlIHN0ZXBzLg",
        "value": 2
    },
    {
        "id": "WW91IGFyZSBtb3JlIGxpa2VseSB0byByZWx5IG9uIGVtb3Rpb25hbCBpbnR1aXRpb24gdGhhbiBsb2dpY2FsIHJlYXNvbmluZyB3aGVuIG1ha2luZyBhIGNob2ljZS4",
        "value": -3
    },
    {
        "id": "WW91IHN0cnVnZ2xlIHdpdGggZGVhZGxpbmVzLg",
        "value": -2
    },
    {
        "id": "WW91IGZlZWwgY29uZmlkZW50IHRoYXQgdGhpbmdzIHdpbGwgd29yayBvdXQgZm9yIHlvdS4",
        "value": 3
    }
],
"gender": "Other"
}
```

I got error 500 {
    "message": "No matches found"
}

**Comment by nastaran-mohammadi** [comment]
same here, any solution?

**Comment by Habubinator** [comment]
> same here, any solution?

Yesterday I've wrote Soni on Instagram, he said that he may check out this issue tomorrow (today)

**Comment by SwapnilSoni1999** [comment]
I've been checking this by today. Please wait and apologies for late responses.

**Comment by Habubinator** [comment]
> Please check now. Should be working fine. If it does then please consider closing the issue.
Still have an issue
`json
{"message":"Unexpected non-whitespace character after JSON at position 5682"}
`

**Comment by Habubinator** [comment]
![image](https://github.com/SwapnilSoni1999/16personalities-api/assets/61784574/cf952023-3d33-43ca-ae1d-255fd0ad2521)
But I should clarify that POST method is fine. Thanks

**Comment by Habubinator** [comment]
Also you may want to change sample responce on frontend part of website

**Comment by Habubinator** [comment]
Also i got this error while testing, is there any issue on my side or api's?
POST - https://www.16personalities-api.com/api/personality/submit

error 422 - Unprocessable Entity
`json
{
    "message": "Unprocessable Entity Error"
}
`
body
`json
{
    "answers": [
    {
        "id": "WW91IHJlZ3VsYXJseSBtYWtlIG5ldyBmcmllbmRzLg",
        "value": 1
    },
    {
        "id": "Q29tcGxleCBhbmQgbm92ZWwgaWRlYXMgZXhjaXRlIHlvdSBtb3JlIHRoYW4gc2ltcGxlIGFuZCBzdHJhaWdodGZvcndhcmQgb25lcy4",
        "value": 1
    },
    {
        "id": "WW91IHVzdWFsbHkgZmVlbCBtb3JlIHBlcnN1YWRlZCBieSB3aGF0IHJlc29uYXRlcyBlbW90aW9uYWxseSB3aXRoIHlvdSB0aGFuIGJ5IGZhY3R1YWwgYXJndW1lbnRzLg",
        "value": 1
    },
    {
        "id": "WW91ciBsaXZpbmcgYW5kIHdvcmtpbmcgc3BhY2VzIGFyZSBjbGVhbiBhbmQgb3JnYW5pemVkLg",
        "value": 1
    },
    {
        "id": "WW91IHVzdWFsbHkgc3RheSBjYWxtLCBldmVuIHVuZGVyIGEgbG90IG9mIHByZXNzdXJlLg",
        "value": 1
    },
    {
        "id": "WW91IGZpbmQgdGhlIGlkZWEgb2YgbmV0d29ya2luZyBvciBwcm9tb3RpbmcgeW91cnNlbGYgdG8gc3RyYW5nZXJzIHZlcnkgZGF1bnRpbmcu",
        "value": 1
    },
    {
        "id": "WW91IHByaW9yaXRpemUgYW5kIHBsYW4gdGFza3MgZWZmZWN0aXZlbHksIG9mdGVuIGNvbXBsZXRpbmcgdGhlbSB3ZWxsIGJlZm9yZSB0aGUgZGVhZGxpbmUu",
        "value": 1
    },
    {
        "id": "UGVvcGxl4oCZcyBzdG9yaWVzIGFuZCBlbW90aW9ucyBzcGVhayBsb3VkZXIgdG8geW91IHRoYW4gbnVtYmVycyBvciBkYXRhLg",
        "value": 1
    },
    {
        "id": "WW91IGxpa2UgdG8gdXNlIG9yZ2FuaXppbmcgdG9vbHMgbGlrZSBzY2hlZHVsZXMgYW5kIGxpc3RzLg",
        "value": 1
    },
    {
        "id": "RXZlbiBhIHNtYWxsIG1pc3Rha2UgY2FuIGNhdXNlIHlvdSB0byBkb3VidCB5b3VyIG92ZXJhbGwgYWJpbGl0aWVzIGFuZCBrbm93bGVkZ2Uu",
        "value": 1
    },
    {
        "id": "WW91IGZlZWwgY29tZm9ydGFibGUganVzdCB3YWxraW5nIHVwIHRvIHNvbWVvbmUgeW91IGZpbmQgaW50ZXJlc3RpbmcgYW5kIHN0cmlraW5nIHVwIGEgY29udmVyc2F0aW9uLg",
        "value": 1
    },
    {
        "id": "WW91IGFyZSBub3QgdG9vIGludGVyZXN0ZWQgaW4gZGlzY3Vzc2lvbnMgYWJvdXQgdmFyaW91cyBpbnRlcnByZXRhdGlvbnMgb2YgY3JlYXRpdmUgd29ya3Mu",
        "value": 1
    },
    {
        "id": "WW91IHByaW9yaXRpemUgZmFjdHMgb3ZlciBwZW9wbGXigJlzIGZlZWxpbmdzIHdoZW4gZGV0ZXJtaW5pbmcgYSBjb3Vyc2Ugb2YgYWN0aW9uLg",
        "value": 1
    },
    {
        "id": "WW91IG9mdGVuIGFsbG93IHRoZSBkYXkgdG8gdW5mb2xkIHdpdGhvdXQgYW55IHNjaGVkdWxlIGF0IGFsbC4",
        "value": 1
    },
    {
        "id": "WW91IHJhcmVseSB3b3JyeSBhYm91dCB3aGV0aGVyIHlvdSBtYWtlIGEgZ29vZCBpbXByZXNzaW9uIG9uIHBlb3BsZSB5b3UgbWVldC4",
        "value": 1
    },
    {
        "id": "WW91IGVuam95IHBhcnRpY2lwYXRpbmcgaW4gdGVhbS1iYXNlZCBhY3Rpdml0aWVzLg",
        "value": 1
    },
    {
        "id": "WW91IGVuam95IGV4cGVyaW1lbnRpbmcgd2l0aCBuZXcgYW5kIHVudGVzdGVkIGFwcHJvYWNoZXMu",
        "value": 1
    },
    {
        "id": "WW91IHByaW9yaXRpemUgYmVpbmcgc2Vuc2l0aXZlIG92ZXIgYmVpbmcgY29tcGxldGVseSBob25lc3Qu",
        "value": 1
    },
    {
        "id": "WW91IGFjdGl2ZWx5IHNlZWsgb3V0IG5ldyBleHBlcmllbmNlcyBhbmQga25vd2xlZGdlIGFyZWFzIHRvIGV4cGxvcmUu",
        "value": 2
    },
    {
        "id": "WW91IGFyZSBwcm9uZSB0byB3b3JyeWluZyB0aGF0IHRoaW5ncyB3aWxsIHRha2UgYSB0dXJuIGZvciB0aGUgd29yc2Uu",
        "value": 2
    },
    {
        "id": "WW91IGVuam95IHNvbGl0YXJ5IGhvYmJpZXMgb3IgYWN0aXZpdGllcyBtb3JlIHRoYW4gZ3JvdXAgb25lcy4",
        "value": 2
    },
    {
        "id": "WW91IGNhbm5vdCBpbWFnaW5lIHlvdXJzZWxmIHdyaXRpbmcgZmljdGlvbmFsIHN0b3JpZXMgZm9yIGEgbGl2aW5nLg",
        "value": -3
    },
    {
        "id": "WW91IGZhdm9yIGVmZmljaWVuY3kgaW4gZGVjaXNpb25zLCBldmVuIGlmIGl0IG1lYW5zIGRpc3JlZ2FyZGluZyBzb21lIGVtb3Rpb25hbCBhc3BlY3RzLg",
        "value": -3
    },
    {
        "id": "WW91IHByZWZlciB0byBkbyB5b3VyIGNob3JlcyBiZWZvcmUgYWxsb3dpbmcgeW91cnNlbGYgdG8gcmVsYXgu",
        "value": -3
    },
    {
        "id": "SW4gZGlzYWdyZWVtZW50cywgeW91IHByaW9yaXRpemUgcHJvdmluZyB5b3VyIHBvaW50IG92ZXIgcHJlc2VydmluZyB0aGUgZmVlbGluZ3Mgb2Ygb3RoZXJzLg",
        "value": -3
    },
    {
        "id": "WW91IHVzdWFsbHkgd2FpdCBmb3Igb3RoZXJzIHRvIGludHJvZHVjZSB0aGVtc2VsdmVzIGZpcnN0IGF0IHNvY2lhbCBnYXRoZXJpbmdzLg",
        "value": -3
    },
    {
        "id": "WW91ciBtb29kIGNhbiBjaGFuZ2UgdmVyeSBxdWlja2x5Lg",
        "value": -3
    },
    {
        "id": "WW91IGFyZSBub3QgZWFzaWx5IHN3YXllZCBieSBlbW90aW9uYWwgYXJndW1lbnRzLg",
        "value": -3
    },
    {
        "id": "WW91IG9mdGVuIGVuZCB1cCBkb2luZyB0aGluZ3MgYXQgdGhlIGxhc3QgcG9zc2libGUgbW9tZW50Lg",
        "value": -3
    },
    {
        "id": "WW91IGVuam95IGRlYmF0aW5nIGV0aGljYWwgZGlsZW1tYXMu",
        "value": -3
    },
    {
        "id": "WW91IHVzdWFsbHkgcHJlZmVyIHRvIGJlIGFyb3VuZCBvdGhlcnMgcmF0aGVyIHRoYW4gb24geW91ciBvd24u",
        "value": -3
    },
    {
        "id": "WW91IGJlY29tZSBib3JlZCBvciBsb3NlIGludGVyZXN0IHdoZW4gdGhlIGRpc2N1c3Npb24gZ2V0cyBoaWdobHkgdGhlb3JldGljYWwu",
        "value": -3
    },
    {
        "id": "V2hlbiBmYWN0cyBhbmQgZmVlbGluZ3MgY29uZmxpY3QsIHlvdSB1c3VhbGx5IGZpbmQgeW91cnNlbGYgZm9sbG93aW5nIHlvdXIgaGVhcnQu",
        "value": -3
    },
    {
        "id": "WW91IGZpbmQgaXQgY2hhbGxlbmdpbmcgdG8gbWFpbnRhaW4gYSBjb25zaXN0ZW50IHdvcmsgb3Igc3R1ZHkgc2NoZWR1bGUu",
        "value": -3
    },
    {
        "id": "WW91IHJhcmVseSBzZWNvbmQtZ3Vlc3MgdGhlIGNob2ljZXMgdGhhdCB5b3UgaGF2ZSBtYWRlLg",
        "value": -3
    },
    {
        "id": "WW91ciBmcmllbmRzIHdvdWxkIGRlc2NyaWJlIHlvdSBhcyBsaXZlbHkgYW5kIG91dGdvaW5nLg",
        "value": -3
    },
    {
        "id": "WW91IGFyZSBkcmF3biB0byB2YXJpb3VzIGZvcm1zIG9mIGNyZWF0aXZlIGV4cHJlc3Npb24sIHN1Y2ggYXMgd3JpdGluZy4",
        "value": -1
    },
    {
        "id": "WW91IHVzdWFsbHkgYmFzZSB5b3VyIGNob2ljZXMgb24gb2JqZWN0aXZlIGZhY3RzIHJhdGhlciB0aGFuIGVtb3Rpb25hbCBpbXByZXNzaW9ucy4",
        "value": 0
    },
    {
        "id": "WW91IGxpa2UgdG8gaGF2ZSBhIHRvLWRvIGxpc3QgZm9yIGVhY2ggZGF5Lg",
        "value": -1
    },
    {
        "id": "WW91IHJhcmVseSBmZWVsIGluc2VjdXJlLg",
        "value": -1
    },
    {
        "id": "WW91IGF2b2lkIG1ha2luZyBwaG9uZSBjYWxscy4",
        "value": 1
    },
    {
        "id": "WW91IGVuam95IGV4cGxvcmluZyB1bmZhbWlsaWFyIGlkZWFzIGFuZCB2aWV3cG9pbnRzLg",
        "value": 2
    },
    {
        "id": "WW91IGNhbiBlYXNpbHkgY29ubmVjdCB3aXRoIHBlb3BsZSB5b3UgaGF2ZSBqdXN0IG1ldC4"
    },
    {
        "id": "SWYgeW91ciBwbGFucyBhcmUgaW50ZXJydXB0ZWQsIHlvdXIgdG9wIHByaW9yaXR5IGlzIHRvIGdldCBiYWNrIG9uIHRyYWNrIGFzIHNvb24gYXMgcG9zc2libGUu",
        "value": 0
    },
    {
        "id": "WW91IGFyZSBzdGlsbCBib3RoZXJlZCBieSBtaXN0YWtlcyB0aGF0IHlvdSBtYWRlIGEgbG9uZyB0aW1lIGFnby4",
        "value": -1
    },
    {
        "id": "WW91IGFyZSBub3QgdG9vIGludGVyZXN0ZWQgaW4gZGlzY3Vzc2luZyB0aGVvcmllcyBvbiB3aGF0IHRoZSB3b3JsZCBjb3VsZCBsb29rIGxpa2UgaW4gdGhlIGZ1dHVyZS4",
        "value": -2
    },
    {
        "id": "WW91ciBlbW90aW9ucyBjb250cm9sIHlvdSBtb3JlIHRoYW4geW91IGNvbnRyb2wgdGhlbS4",
        "value": 1
    },
    {
        "id": "V2hlbiBtYWtpbmcgZGVjaXNpb25zLCB5b3UgZm9jdXMgbW9yZSBvbiBob3cgdGhlIGFmZmVjdGVkIHBlb3BsZSBtaWdodCBmZWVsIHRoYW4gb24gd2hhdCBpcyBtb3N0IGxvZ2ljYWwgb3IgZWZmaWNpZW50Lg",
        "value": -1
    },
    {
        "id": "WW91ciBwZXJzb25hbCB3b3JrIHN0eWxlIGlzIGNsb3NlciB0byBzcG9udGFuZW91cyBidXJzdHMgb2YgZW5lcmd5IHRoYW4gb3JnYW5pemVkIGFuZCBjb25zaXN0ZW50IGVmZm9ydHMu",
        "value": -3
    },
    {
        "id": "V2hlbiBzb21lb25lIHRoaW5rcyBoaWdobHkgb2YgeW91LCB5b3Ugd29uZGVyIGhvdyBsb25nIGl0IHdpbGwgdGFrZSB0aGVtIHRvIGZlZWwgZGlzYXBwb2ludGVkIGluIHlvdS4",
        "value": 0
    },
    {
        "id": "WW91IHdvdWxkIGxvdmUgYSBqb2IgdGhhdCByZXF1aXJlcyB5b3UgdG8gd29yayBhbG9uZSBtb3N0IG9mIHRoZSB0aW1lLg",
        "value": 2
    },
    {
        "id": "WW91IGJlbGlldmUgdGhhdCBwb25kZXJpbmcgYWJzdHJhY3QgcGhpbG9zb3BoaWNhbCBxdWVzdGlvbnMgaXMgYSB3YXN0ZSBvZiB0aW1lLg",
        "value": 0
    },
    {
        "id": "WW91IGZlZWwgbW9yZSBkcmF3biB0byBidXN5LCBidXN0bGluZyBhdG1vc3BoZXJlcyB0aGFuIHRvIHF1aWV0LCBpbnRpbWF0ZSBwbGFjZXMu",
        "value": 0
    },
    {
        "id": "SWYgYSBkZWNpc2lvbiBmZWVscyByaWdodCB0byB5b3UsIHlvdSBvZnRlbiBhY3Qgb24gaXQgd2l0aG91dCBuZWVkaW5nIGZ1cnRoZXIgcHJvb2Yu",
        "value": -2
    },
    {
        "id": "WW91IG9mdGVuIGZlZWwgb3ZlcndoZWxtZWQu",
        "value": -3
    },
    {
        "id": "WW91IGNvbXBsZXRlIHRoaW5ncyBtZXRob2RpY2FsbHkgd2l0aG91dCBza2lwcGluZyBvdmVyIGFueSBzdGVwcy4",
        "value": -1
    },
    {
        "id": "WW91IHByZWZlciB0YXNrcyB0aGF0IHJlcXVpcmUgeW91IHRvIGNvbWUgdXAgd2l0aCBjcmVhdGl2ZSBzb2x1dGlvbnMgcmF0aGVyIHRoYW4gZm9sbG93IGNvbmNyZXRlIHN0ZXBzLg",
        "value": 0
    },
    {
        "id": "WW91IGFyZSBtb3JlIGxpa2VseSB0byByZWx5IG9uIGVtb3Rpb25hbCBpbnR1aXRpb24gdGhhbiBsb2dpY2FsIHJlYXNvbmluZyB3aGVuIG1ha2luZyBhIGNob2ljZS4",
        "value": -3
    },
    {
        "id": "WW91IHN0cnVnZ2xlIHdpdGggZGVhZGxpbmVzLg",
        "value": -1
    },
    {
        "id": "WW91IGZlZWwgY29uZmlkZW50IHRoYXQgdGhpbmdzIHdpbGwgd29yayBvdXQgZm9yIHlvdS4",
        "value": 1
    }
],
"gender": "Other"
}
`

**Comment by SwapnilSoni1999** [comment]
Please check again and update on the issue
Thanks. I've checked from my side its working fine

**Comment by vvknyazev** [comment]
still having this problem
![Postman_1I12wBKe8R](https://github.com/SwapnilSoni1999/16personalities-api/assets/42218848/25470966-b336-4d15-b153-a79c174154a1)

**Comment by nikitalokhmachev-ai** [comment]
Please do @Habubinator ! Thanks.

**Comment by Habubinator** [comment]
> Please do @Habubinator ! Thanks.
Here it is 
[en.json](https://github.com/SwapnilSoni1999/16personalities-api/files/15480345/en.json)

**Comment by SwapnilSoni1999** [comment]
I'm currently fixing it sorry for inconvenience

**Comment by SwapnilSoni1999** [comment]
fixed! 
Hope everything is working fine. I've tested from my end. Please close the issue if its resolved.

**Comment by Habubinator** [comment]
All is cool now, thanks for distracting from your current work to fix the issue!
